# Generated by Django 4.2.4 on 2023-11-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image1',
            field=models.ImageField(null=True, upload_to='event_images/<django.db.models.fields.SlugField>'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image2',
            field=models.ImageField(null=True, upload_to='event_images/<django.db.models.fields.SlugField>'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image3',
            field=models.ImageField(null=True, upload_to='event_images/<django.db.models.fields.SlugField>'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image4',
            field=models.ImageField(null=True, upload_to='event_images/<django.db.models.fields.SlugField>'),
        ),
    ]
