# Generated by Django 4.2.4 on 2023-11-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pictures/<django.db.models.fields.CharField>'),
        ),
    ]
